export const PRODUCT_CATEGORIES = [
  { label: "Cep Telefonu ve Tablet", href: "/cep-telefonu-ve-tablet", value: "cep-telefonu-ve-tablet" },
  { label: "Powerbank", href: "/powerbank", value: "powerbank" },
  { label: "Şarj Cihazı", href: "/sarj-cihazi", value: "sarj-cihazi" },
  { label: "Kablo", href: "/kablo", value: "kablo" },
  { label: "Ses ve Müzik", href: "/ses-ve-muzik", value: "ses-ve-muzik" },
  { label: "Araç Tutucu", href: "/arac-tutucu", value: "arac-tutucu" },
  { label: "Aksesurlar", href: "/aksesuarlar", value: "aksesuarlar" },
  { label: "Giyilebilir Teknoloji", href: "/giyilebilir-teknoloji", value: "giyilebilir-teknoloji" },
  { label: "Hafıza Ürünleri", href: "/hafiza-urunleri", value: "hafiza-urunleri" },
  { label: "Çevre Birimleri", href: "/cevre-birimleri", value: "cevre-birimleri" },
  { label: "Telefon Kılıfı", href: "/telefon-kilifi", value: "telefon-kilifi" },
  { label: "Telefon Ekran Koruyucu", href: "/telefon-ekran-koruyucu", value: "telefon-ekran-koruyucu" },
  { label: "Tablet Kılıfı", href: "/tablet-kilifi", value: "tablet-kilifi" },
  { label: "Tablet Ekran Koruyucu", href: "/tablet-ekran-koruyucu", value: "tablet-ekran-koruyucu" },
];
